# Data Tranformation

In [22]:
# Dependencies
import pandas as pd 
import numpy as np

In [23]:
filepath = f"CA_chemengjobs.csv"
df = pd.read_csv(filepath, index_col=0)
df

,Job Title Index,Job ID,Job Title,Company Name,Company Location,Link
0,1,p_8cbde469b526f937,Municipal Designer,"Gannett Fleming, Inc.","Toronto, ON",https://ca.indeed.com/rc/clk?jk=8cbde469b526f9...
1,1,p_3afb56f3ae24cb94,Sessional Lecturer - MIE550H1S: Advanced Momen...,University of Toronto,"Toronto, ON",https://ca.indeed.com/rc/clk?jk=3afb56f3ae24cb...
2,1,p_476ef0c6c3f20408,Mechanical Engineering Graduate,AECOM,"Winnipeg, MB",https://ca.indeed.com/rc/clk?jk=476ef0c6c3f204...
3,1,p_ec1badbed12494f1,Applications Engineer,Technel Engineering Inc.,"Woodbridge, ON",https://ca.indeed.com/company/Technel-Engineer...
4,1,p_6c9bf8399ff4fed6,Structural Engineering Graduate,AECOM,"Winnipeg, MB",https://ca.indeed.com/rc/clk?jk=6c9bf8399ff4fe...
...,...,...,...,...,...,...
439,12,p_66cdb9a2c5c6f939,Waste Managment Specialist,GHD,"Richmond, BC",https://ca.indeed.com/rc/clk?jk=66cdb9a2c5c6f9...
440,12,p_e591b271e7e17473,Junior R&D Engineer (Temporary 1 year),Enerkem Inc.,"Westbury, QC",https://ca.indeed.com/rc/clk?jk=e591b271e7e174...
441,12,p_bb32230b8141d238,Junior Process Engineer,Enerkem Inc.,"Montréal, QC",https://ca.indeed.com/rc/clk?jk=bb32230b8141d2...
442,12,p_1af748435f113fad,Intermediate Soil Scientist,Matrix Solutions Inc.,"Calgary, AB",https://ca.indeed.com/rc/clk?jk=1af748435f113f...
443,12,p_66cdb9a2c5c6f939,Waste Managment Specialist,GHD,"Richmond, BC",https://ca.indeed.com/rc/clk?jk=66cdb9a2c5c6f9...

In [26]:
# Drop duplicates and reset index

df.drop_duplicates(subset=['Job ID'],keep='first', inplace=True, ignore_index=True)
df.reset_index()
df

,Job Title Index,Job ID,Job Title,Company Name,Company Location,Link
0,1,p_8cbde469b526f937,Municipal Designer,"Gannett Fleming, Inc.","Toronto, ON",https://ca.indeed.com/rc/clk?jk=8cbde469b526f9...
1,1,p_3afb56f3ae24cb94,Sessional Lecturer - MIE550H1S: Advanced Momen...,University of Toronto,"Toronto, ON",https://ca.indeed.com/rc/clk?jk=3afb56f3ae24cb...
2,1,p_476ef0c6c3f20408,Mechanical Engineering Graduate,AECOM,"Winnipeg, MB",https://ca.indeed.com/rc/clk?jk=476ef0c6c3f204...
3,1,p_ec1badbed12494f1,Applications Engineer,Technel Engineering Inc.,"Woodbridge, ON",https://ca.indeed.com/company/Technel-Engineer...
4,1,p_6c9bf8399ff4fed6,Structural Engineering Graduate,AECOM,"Winnipeg, MB",https://ca.indeed.com/rc/clk?jk=6c9bf8399ff4fe...
...,...,...,...,...,...,...
254,11,p_8a1123325ba270e3,Electrical EIT - Vancouver,Ausenco,"Vancouver, BC",https://ca.indeed.com/rc/clk?jk=8a1123325ba270...
255,11,p_7c25592e995b383c,Sr. Firmware Engineer,Neurio Technology,"Vancouver, BC",https://ca.indeed.com/rc/clk?jk=7c25592e995b38...
256,11,p_66cdb9a2c5c6f939,Waste Managment Specialist,GHD,"Richmond, BC",https://ca.indeed.com/rc/clk?jk=66cdb9a2c5c6f9...
257,11,p_15e52d63cdf26012,Senior Geotechnical Engineer,AECOM,"Edmonton, AB",https://ca.indeed.com/rc/clk?jk=15e52d63cdf260...
258,12,p_1af748435f113fad,Intermediate Soil Scientist,Matrix Solutions Inc.,"Calgary, AB",https://ca.indeed.com/rc/clk?jk=1af748435f113f...

In [27]:
# Remove the Link column
df = df[["Job Title Index", "Job ID", "Job Title", "Company Name", "Company Location"]]

df.head()

,Job Title Index,Job ID,Job Title,Company Name,Company Location
0,1,p_8cbde469b526f937,Municipal Designer,"Gannett Fleming, Inc.","Toronto, ON"
1,1,p_3afb56f3ae24cb94,Sessional Lecturer - MIE550H1S: Advanced Momen...,University of Toronto,"Toronto, ON"
2,1,p_476ef0c6c3f20408,Mechanical Engineering Graduate,AECOM,"Winnipeg, MB"
3,1,p_ec1badbed12494f1,Applications Engineer,Technel Engineering Inc.,"Woodbridge, ON"
4,1,p_6c9bf8399ff4fed6,Structural Engineering Graduate,AECOM,"Winnipeg, MB"

In [28]:
# Check if there is any is null in the dataframe
df.isnull().sum()

Job Title Index     0
Job ID              0
Job Title           0
Company Name        0
Company Location    0
dtype: int64

In [29]:
# Find unique job titles and count
df["Job Title"].value_counts()

Software Development Engineer                              4
Project Coordinator                                        3
Senior Software Engineer, Full Stack (Java, Javascript)    2
Junior Software Engineer                                   2
Senior Geotechnical Engineer                               2
                                                          ..
FULLSTACK DEVELOPPER & DATA ENGINEER                       1
Tier 3 Systems Engineer                                    1
Senior Data Engineer (Remote)                              1
Junior Biologist/Scientist                                 1
Mechanical Engineer, P.Eng                                 1
Name: Job Title, Length: 241, dtype: int64

In [30]:
# Group by location and count
df_location = df.groupby(["Company Location"]).count()
df_location = df_location[["Job ID"]].sort_values(["Job ID"], ascending=False)
df_location.head(50)

                                                    Job ID
Company Location
Toronto, ON                                             53
Vancouver, BC                                           43
Montréal, QC                                            17
Ottawa, ON                                              14
Mississauga, ON                                         10
Calgary, AB                                              8
Edmonton, AB                                             5
Markham, ON                                              4
Saskatoon, SK                                            4
Winnipeg, MB                                             4
Burlington, ON                                           4
Guelph, ON                                               3
Kitchener, ON                                            3
Regina, SK                                               3
Waterloo, ON                                             3
Greater Sudbury, ON                                      3
Oakville, ON                                             3
Burnaby, BC                                              3
Halifax, NS                                              3
Brampton, ON                                             3
Canada                                                   2
Sydney, NS                                               2
Nelson, BC                                               2
Dartmouth, NS                                            2
Ontario                                                  2
Richmond, BC                                             2
Surrey, BC                                               2
Yellowknife, NT                                          2
Langley, BC                                              2
University of British Columbia (Vancouver campu...       2
Hamilton, ON                                             2
Vaughan, ON                                              2
Fort St. John, BC                                        2
Sooke, BC                                                1
Scarborough, ON                                          1
Whitehorse, YT                                           1
Shawinigan, QC                                           1
Whitby, ON                                               1
Sidney, BC                                               1
Westbury, QC                                             1
Squamish, BC                                             1
Thurso, QC                                               1
St. John's, NL                                           1
Vaudreuil-Dorion, QC                                     1
Woodbridge, ON                                           1
St. Marys, ON                                            1
Saint John, NB                                           1
Windsor, ON                                              1
Barrie, ON                                               1
Saint Andrews, NB                                        1

In [31]:
# Filter job titles that has string "Junior" 

df_junior = df[df['Job Title'].str.contains('Junior', na=False, regex=False)]
df_junior

,Job Title Index,Job ID,Job Title,Company Name,Company Location
19,1,p_50c173dda09569e5,Junior/intermediate Project and Process Engineers,Atlas BA Consulting Engineering,"Calgary, AB"
20,1,p_6386f4418f561175,Junior Traffic Engineer (EIT),McElhanney Ltd.,"Surrey, BC"
26,1,p_cb14c70f08d04d42,Junior Acoustics & Vibration Specialist/Engineer,Wood Plc,"Oakville, ON"
47,3,p_bb32230b8141d238,Junior Process Engineer,Enerkem Inc.,"Montréal, QC"
48,3,p_1172f615ab98a9f7,"Engineer - Process, Junior",Linamar Corp,"Guelph, ON"
49,3,p_34a2c582637605d1,Junior Process Engineer (Open),SNC-Lavalin,"Mississauga, ON"
50,3,p_3fd3f65e2782b38c,Junior Process/Mechanical Engineer,SNC-Lavalin,"Mississauga, ON"
52,4,p_e591b271e7e17473,Junior R&D Engineer (Temporary 1 year),Enerkem Inc.,"Westbury, QC"
62,5,p_ca95a9864bd1f987,Junior Project Engineer,Kanin Energy,"Calgary, AB"
63,5,p_a102b149716a1f6f,Junior Project Management Engineer,Vision Performance Group Inc.,"Burlington, ON"
64,5,p_a6e156e2ad3c60e7,Junior Project Engineer,Raymond EMC,"Ottawa, ON"
67,6,p_92431fd813867b87,Driver (Junior Maintenance Mechanic),Gateway Mechanical Services,"Edmonton, AB"
71,6,p_b0d6ceae863ec1ff,Junior Administrative Assistant,BDO,"Essex, ON"
72,6,p_2d00e0f49a5cc4b0,Junior/Intermediate Community Health/Socio-Eco...,Stantec,"Sidney, BC"
73,6,p_2ad71a6022560922,Conseiller Quantitatif Junior-(H/F),Société Générale,"Montréal, QC"
74,6,p_301f357c0a352de1,Accountant (Junior),CBRE,"Toronto, ON"
75,6,p_b00e7e0d2aa26efe,Junior Data Scientist,Global Spatial Technology Solutions Inc.,"Dartmouth, NS"
81,6,p_824029bf3e26ce0d,Responsable des Ventes (Junior),PME MTL Centre-Est,"Montréal, QC"
82,6,p_3502404efda09422,Junior Data Scientist,Indigo Park,"Toronto, ON"
83,6,pj_d280c51b15aaf4d7,Junior Accounting Clerk,Confidential Employer,"Scarborough, ON"
85,6,p_c58008ff30217042,Junior Accounts Receivable Cash Specialist - O...,O2E Brands,"Vancouver, BC"
88,6,p_215114284f7983bc,"GBP - Junior Programmer / Analyst, Client Serv...",Scotiabank,"Toronto, ON"
105,7,p_025710d68872caf6,Junior Alternative Fuel Product Engineer,Westport Fuel Systems,"Cambridge, ON"
117,7,p_4d44f61f48f8ba7a,"Automation Technician, Junior",Linamar Corp,"Guelph, ON"
135,8,p_95d1ab114167e09f,Junior to Intermediate Systems Engineer -Ottaw...,MDA,"Ottawa, ON"
136,8,p_05a20d3143448c81,Junior Software Engineer,Telesat,"Ottawa, ON"
141,8,p_7aa0efaa4f51df67,Junior Electrical Engineer,"Ultra Maritime, Maritime Systems","Dartmouth, NS"
145,8,p_b9e2417a694bd88f,"Junior Asset Optimization Consultant, Bilingua...",Ausenco,"Montréal, QC"
163,10,p_776962f590f68019,Junior UX Designer,Achievers,"Toronto, ON"
168,10,p_d789b7a75c04f1a8,Junior Java Developer,Amiga Informatics,"Toronto, ON"
169,10,p_12a65984332f5c11,Junior Software Developer,World Education Services,"Toronto, ON"
172,10,pj_3c7e9fb1f2d7f2e5,Junior Power BI Developer - 300476,Procom,"Richmond, BC"
174,10,p_27c8e634cd7326b0,Junior Lead Generator,Allied Technical Sales,"Greater Toronto Area, ON"
184,10,p_2489ef865e8b7bc0,Junior Mechanical Engineer,Tramac Solutions,"Vaudreuil-Dorion, QC"
185,10,pj_be9fa0e1cebd79c9,Junior Java/ Big Data (Hadoop Ecosystem) Devel...,Procom,"Toronto, ON"
194,10,p_1ed1893f5f7da633,Junior Mine Closure Specialist,Golder Associates,"Greater Sudbury, ON"
210,10,p_f32ed3a8af7dc456,Junior Software Engineer,ThoughtWire,"Toronto, ON"
215,10,p_15cbfb7bd2ae642e,Hemmera - Junior or Intermediate Environmental...,Ausenco,"Whitehorse, YT"
220,10,p_781703f4a87379dc,Junior Biologist/Scientist,Jacobs,"Toronto, ON"
224,10,p_47b9353b933891bf,Junior Field Technician / Field Engineer,Tower Engineering Professionals,"Calgary, AB"

In [32]:
# Find unique job titles and count
df_junior["Job Title"].value_counts()

Junior Data Scientist                                              2
Junior Software Engineer                                           2
Junior Project Engineer                                            2
Hemmera - Junior or Intermediate Environmental Scientist/Eng...    1
Responsable des Ventes (Junior)                                    1
GBP - Junior Programmer / Analyst, Client Services & Solutio...    1
Automation Technician, Junior                                      1
Junior Accounting Clerk                                            1
Junior Asset Optimization Consultant, Bilingual - (Montreal)       1
Junior Acoustics & Vibration Specialist/Engineer                   1
Junior Field Technician / Field Engineer                           1
Junior Project Management Engineer                                 1
Junior Administrative Assistant                                    1
Junior/intermediate Project and Process Engineers                  1
Junior Traffic Engineer (EIT)                                      1
Junior Lead Generator                                              1
Conseiller Quantitatif Junior-(H/F)                                1
Junior Biologist/Scientist                                         1
Engineer - Process, Junior                                         1
Junior Software Developer                                          1
Junior R&D Engineer (Temporary 1 year)                             1
Junior Power BI Developer - 300476                                 1
Junior to Intermediate Systems Engineer -Ottawa or Vancouver       1
Accountant (Junior)                                                1
Junior/Intermediate Community Health/Socio-Economic Speciali...    1
Junior Accounts Receivable Cash Specialist - O2E Brands - 12...    1
Junior Mine Closure Specialist                                     1
Junior Java Developer                                              1
Junior Mechanical Engineer                                         1
Junior Process/Mechanical Engineer                                 1
Junior Process Engineer (Open)                                     1
Junior Process Engineer                                            1
Junior UX Designer                                                 1
Driver (Junior Maintenance Mechanic)                               1
Junior Java/ Big Data (Hadoop Ecosystem) Developer - 300484        1
Junior Alternative Fuel Product Engineer                           1
Junior Electrical Engineer                                         1
Name: Job Title, dtype: int64

In [33]:
# Group by location and count
df_junior_location = df_junior.groupby(["Company Location"]).count()
df_junior_location = df_junior_location[["Job ID"]].sort_values(["Job ID"], ascending=False)
df_junior_location.head(50)

                          Job ID
Company Location
Toronto, ON                    9
Montréal, QC                   4
Calgary, AB                    3
Ottawa, ON                     3
Dartmouth, NS                  2
Guelph, ON                     2
Mississauga, ON                2
Burlington, ON                 1
Scarborough, ON                1
Westbury, QC                   1
Vaudreuil-Dorion, QC           1
Vancouver, BC                  1
Surrey, BC                     1
Sidney, BC                     1
Oakville, ON                   1
Richmond, BC                   1
Greater Toronto Area, ON       1
Greater Sudbury, ON            1
Essex, ON                      1
Edmonton, AB                   1
Cambridge, ON                  1
Whitehorse, YT                 1

In [34]:
# Filter job titles that has string "Jr" 

df_jr = df[df['Job Title'].str.contains('Jr', na=False, regex=False)]
df_jr

,Job Title Index,Job ID,Job Title,Company Name,Company Location
46,3,pj_5c861f71660bdd90,Jr. Automation Process Engineer,Crystal Claire Cosmetics Inc,"Toronto, ON"
211,10,p_b625120a16d5d7f6,Jr. Android Engineer,Trader Corporation,"Toronto, ON"
217,10,pj_630401d8006afe63,Jr. iOS Engineer,autoTRADER.ca,"Montréal, QC"
221,10,p_d30dead5b09ed169,Jr Data Integration Engineer,KORE Software,"Vancouver, BC"

In [35]:
# Find unique job titles and count
df_jr["Job Title"].value_counts()

Jr. Automation Process Engineer    1
Jr Data Integration Engineer       1
Jr. iOS Engineer                   1
Jr. Android Engineer               1
Name: Job Title, dtype: int64

In [36]:
# Group by location and count
df_jr_location = df_jr.groupby(["Company Location"]).count()
df_jr_location = df_jr_location[["Job ID"]].sort_values(["Job ID"], ascending=False)
df_jr_location.head(50)

                  Job ID
Company Location
Toronto, ON            2
Montréal, QC           1
Vancouver, BC          1

In [37]:
# Filter job titles that has string "EIT" 

df_EIT = df[df['Job Title'].str.contains('EIT', na=False, regex=False)]
df_EIT

,Job Title Index,Job ID,Job Title,Company Name,Company Location
7,1,p_c48406d023594c71,Field Production Engineer (EIT),Canlin Energy Corporation,"Rocky Mountain House, AB"
10,1,pj_a1f63b57ca0e6770,Electrical EIT,Core One Consulting Ltd.,"Montréal, QC"
14,1,p_e1976b7691e999b0,Engineer-in-Training (EIT),City of Edmonton,"Edmonton, AB"
18,1,p_e1d11f33349edad9,"Designer, EIT - Bridges",WSP,"Regina, SK"
20,1,p_6386f4418f561175,Junior Traffic Engineer (EIT),McElhanney Ltd.,"Surrey, BC"
21,1,p_9040853200753110,Geotechnical/Civil EIT,exp,"Greater Sudbury, ON"
66,6,p_aa4dae30a4dba478,Building Science EIT / Technologist - Minimum ...,R and C Engineering Inc.,"Toronto, ON"
254,11,p_8a1123325ba270e3,Electrical EIT - Vancouver,Ausenco,"Vancouver, BC"

In [38]:
# Find unique job titles and count
df_EIT["Job Title"].value_counts()

Building Science EIT / Technologist - Minimum 1 year of expe...    1
Junior Traffic Engineer (EIT)                                      1
Geotechnical/Civil EIT                                             1
Engineer-in-Training (EIT)                                         1
Field Production Engineer (EIT)                                    1
Electrical EIT                                                     1
Electrical EIT - Vancouver                                         1
Designer, EIT - Bridges                                            1
Name: Job Title, dtype: int64

In [39]:
# Group by location and count
df_EIT_location = df_EIT.groupby(["Company Location"]).count()
df_EIT_location = df_EIT_location[["Job ID"]].sort_values(["Job ID"], ascending=False)
df_EIT_location.head(50)

                          Job ID
Company Location
Edmonton, AB                   1
Greater Sudbury, ON            1
Montréal, QC                   1
Regina, SK                     1
Rocky Mountain House, AB       1
Surrey, BC                     1
Toronto, ON                    1
Vancouver, BC                  1

In [40]:
# Filter job titles that has string "Engineer-in-training" 

df_EIT_long = df[df['Job Title'].str.contains('Engineer-in-Training', na=False, regex=False)]
df_EIT_long

,Job Title Index,Job ID,Job Title,Company Name,Company Location
14,1,p_e1976b7691e999b0,Engineer-in-Training (EIT),City of Edmonton,"Edmonton, AB"
22,1,p_feba946509c13a2c,Transportation Technologist / Engineer-in-Trai...,C.F. Crozier & Associates Inc.,"Milton, ON"
35,2,p_0af954bb7dd543aa,Civil Engineer-in-Training,Urban Systems,"Fort St. John, BC"
41,2,p_cc8f2cd85e3ab89e,Development Coordinator (Engineer-in-Training),Canadian Solar,"Calgary, AB"

In [41]:
# Find unique job titles and count
df_EIT_long["Job Title"].value_counts()

Engineer-in-Training (EIT)                                     1
Transportation Technologist / Engineer-in-Training (E.I.T.)    1
Development Coordinator (Engineer-in-Training)                 1
Civil Engineer-in-Training                                     1
Name: Job Title, dtype: int64

In [42]:
# Group by location and count
df_EIT_long_location = df_EIT_long.groupby(["Company Location"]).count()
df_EIT_long_location = df_EIT_long_location[["Job ID"]].sort_values(["Job ID"], ascending=False)
df_EIT_long_location.head(50)

                   Job ID
Company Location
Calgary, AB             1
Edmonton, AB            1
Fort St. John, BC       1
Milton, ON              1